### ISSUE TITLE
This man is mean

### ISSUE THREAD

**Issue by TheBestCoderPenguin** [DarkoPendragon/discord.js-chatbot#1]
This man is so mean and he was mean to be because he was mean. He should be banned.

**Comment by TheBestCoderPenguin** [comment]
same

**Comment by TheBestCoderPenguin** [comment]
yeah ban him

**Comment by DarkoPendragon** [comment]
TheBestCoderPenguin,

I'm sorry to hear about this issue!

Our team values our customers time, money, and being able to have a healthy relashonship with you, we will get to the bottom of this!

Thank you,
- Karen Form Finance
